.TH "ncmpc" "1" "0.10.0" "Kalle Wallin" ""
.SH "NAME"
ncmpc \- curses Music Player Daemon (MPD) client.
.SH "SYNOPSIS"
.B ncmpc
[options]
.SH "DESCRIPTION"
ncmpc is  a client for MPD, the Music Player Daemon. 
ncmpc connects to a MPD running on a machine on the local 
network.

By default, ncmpc connects to localhost:2100. 
This can be changed either at compile\-time, or by exporting the 
MPD_HOST and MPD_PORT environment variables, or by the command line
options \-\-host and \-\-port.

$ ncmpc \-\-host=musicserver \-\-port=44000

To use a password with mpd, set MPD_HOST to password@host 
or use the command line option \-\-password. Values from 
the command line overrides values from the environment.

Read more about MPD on http://www.musicpd.org

.SH "OPTIONS"
.TP 
.B \-?, \-\-help
Display help.
.TP 
.B \-V,  \-\-version
Display version information.
.TP 
.B \-c,  \-\-colors
Enable colors.
.TP 
.B \-C,  \-\-no\-colors
Disable colors.
.TP 
.B \-e,  \-\-exit
Exit on connection errors. The default is to reconnect.
.TP 
.B \-h, \-\-host=HOSTNAME
Specify MPD host.
.TP 
.B \-p, \-\-port=PORT
Connect to server on PORT.
.TP 
.B \-P, \-\-password=PASSWORD
Connect top MPD with a password.
.TP 
Mandatory or optional arguments to long options are also mandatory or optional for any corresponding short options.
.SH "KEYS"
You can view ncmpc's key bindings by pressing F1 (help) when 
ncmpc is running.
.SH "CONFIGURATION FILE"
When ncmpc start it read user setting from ~/.ncmpcrc. An example file ncmpcrc.sample should be provided with ncmpc.


.SH "SEE ALSO"
mpc(1), MPD(1)
