---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'lyrics/**'
      - 'po/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'lyrics/**'
      - 'po/**'
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    env:
      CC: 'ccache gcc-10'
      CXX: 'ccache g++-10'
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: linux

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            meson \
            g++-10 \
            libncursesw5-dev \
            libncurses5-dev \
            libpcre2-dev \
            libmpdclient-dev

      - name: Full Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/full
          setup-options: -Ddocumentation=disabled -Dlyrics_screen=true -Dchat_screen=true

      - name: Mini Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/mini
          setup-options: -Ddocumentation=disabled -Dbuildtype=minsize -Db_ndebug=true -Db_lto=true -Dauto_features=disabled -Dcurses=ncurses -Dcolors=false -Dmultibyte=false -Dtcp=false -Dasync_connect=false -Dmini=true

  build-macos:
    runs-on: macos-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: macos

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          brew install \
            meson ninja \
            ncurses \
            pcre2 \
            libmpdclient

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output
          setup-options: -Ddocumentation=disabled -Dlyrics_screen=true -Dchat_screen=true
