---
name: CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'lyrics/**'
      - 'po/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'lyrics/**'
      - 'po/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build-linux:
    strategy:
      matrix:
        compiler: [gcc14, gcc11, gcc10]
        include:
          - compiler: gcc14
            os: ubuntu-24.04
            cc: gcc-14
            cxx: g++-14
            packages: g++-14
          - compiler: gcc11
            os: ubuntu-22.04
            cc: gcc-11
            cxx: g++-11
            packages: g++-11
          - compiler: gcc10
            os: ubuntu-20.04
            cc: gcc-10
            cxx: g++-10
            packages: g++-10
          - compiler: clang
            os: ubuntu-24.04
            cc: clang
            cxx: clang++
            packages: clang

    runs-on: ${{ matrix.os }}

    env:
      CC: ccache ${{ matrix.cc }}
      CXX: ccache ${{ matrix.cxx }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            ncmpc \
            ${{ matrix.packages }} \
            libncursesw5-dev \
            libncurses5-dev \
            libpcre2-dev \
            libmpdclient-dev

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.compiler }}

      - name: Full Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/full
          setup-options: -Ddocumentation=disabled -Dlyrics_screen=true -Dchat_screen=true

      - name: Mini Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/mini
          setup-options: -Ddocumentation=disabled -Dbuildtype=minsize -Db_ndebug=true -Db_lto=true -Dauto_features=disabled -Dcurses=ncurses -Dcolors=false -Dmultibyte=false -Dasync_connect=false -Dmini=true

  build-macos:
    runs-on: macos-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          brew install \
            meson ninja \
            ccache \
            ncurses \
            pcre2 \
            libmpdclient

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: macos

      - name: Full Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/full
          setup-options: -Ddocumentation=disabled -Dlyrics_screen=true -Dchat_screen=true

      - name: Mini Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output/mini
          setup-options: -Ddocumentation=disabled -Dbuildtype=minsize -Db_ndebug=true -Db_lto=true -Dauto_features=disabled -Dcurses=ncurses -Dcolors=false -Dmultibyte=false -Dasync_connect=false -Dmini=true
